### ISSUE TITLE
Import failures in react native 

### ISSUE THREAD

**Issue by maniac-tech** [saurabhgupta050890/transaction-sms-parser#17]
- **I'm submitting a ...**
 - [ ] bug report
 - [ ] feature request
 - [ ] question about the decisions made in the repository
 - [x] question about how to use this project

- **Summary**
I intend to use this in a react-native based application, but I'm facing an error while importing it. Have you tested it ?

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
The error I see in expo is:

`Unable to resolve "transaction-sms-parser" from "components/x/y.js"`

**Comment by maniac-tech** [comment]
This seems to be related to the missing index.js at the root in the typescript package 🤔

**Comment by saurabhgupta050890** [comment]
Have not used with react native but have been using with in other FE projects. Don't think this should be an issue.
Try clearing npm cache and removing node_modules.

**Comment by maniac-tech** [comment]
> Have not used with react native but have been using with in other FE projects. Don't think this should be an issue. Try clearing npm cache and removing node_modules.

I figured the issue. It is the lack of index.js, I was able to bypass this issue by tweaking the import as below:

```
import { getTransactionInfo } from 'transaction-sms-parser/dist/lib';
```
